name: CI

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security:
    uses: chlip2/olcs-backend/.github/workflows/php-security.yml@feature-bl-16691-update-actions-to-node-20
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  static-analysis:
    uses: chlip2/olcs-backend/.github/workflows/php-static.yml@feature-bl-16691-update-actions-to-node-20
    with:
      php-version: '8.0'

  tests:
    uses: chlip2/olcs-backend/.github/workflows/php-tests.yml@feature-bl-16691-update-actions-to-node-20
    with:
      php-versions: '["8.0"]'
      fail-fast: false
